name: 'monkeytype'
version: '1.0.0'
profile: 'monkeytype'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  monkeytype:
      +materialized: table
      +schema: analytics