version: 2

# Import source tables for reference in models 

sources:
  - name: monkeytype 
    database: "{{ env_var('GOOGLE_CLOUD_PROJECT_ID') }}"
    schema: monkeytype_stats
    tables:
      - name: activity
      - name: best_results
      - name: results
      - name: stats
      