version: 2

# Import source data for reference in models 

sources:
  - name: monkeytype 
    database: global-grammar-449122-b6
    schema: monkeytype_stats
    tables:
      - name: activity
      - name: best_results
      - name: results
      - name: stats
      