-- Data generated by calling api, may be more fresh than "results" table which is manually updated
-- All columns except "started_tests" could be calculated with the help of "results" table

select *
from {{ source('monkeytype', 'stats') }}